services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: magapp_local
    container_name: magapp_local
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "2718:2718" # marimo
    command: /start
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: magapp_postgres
    volumes:
      - magapp_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  magapp_postgres_data: { }