services: 
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: magapp_local
    container_name: magapp_local
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "2718:2718" # marimo
    command: /start