# fly.toml app configuration file generated for magapp-weathered-moon-2824 on 2024-03-01T09:58:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'magapp-weathered-moon-2824'
primary_region = 'gru'
# The command to run when you run the fly console command.
console_command = '/code/manage.py shell'

[build]
  dockerfile = "docker/prod/Dockerfile"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="magapp_db"
  destination="/mnt/magapp_db"

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
