# Generated by Django 5.1.5 on 2025-04-14 11:59

import django.db.models.deletion
import magapp.base.utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_recipe_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', magapp.base.utils.models.LowerCharField(help_text='Titulo da refeição', max_length=64, verbose_name='título')),
                ('slug', models.SlugField(editable=False, error_messages={'unique': 'Este slug já existe.'}, max_length=64, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'refeições',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(models.F('slug'), name='unique_meal_slug')],
            },
        ),
    ]
