# Generated by Django 5.1.5 on 2025-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('recipes', '0003_recipe_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(related_name='meals', to='recipes.recipe'),
        ),
    ]
