# Generated by Django 3.2.12 on 2022-04-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título da receita.', max_length=64, verbose_name='título')),
                ('description', models.TextField(help_text='Breve descrição da receita', verbose_name='descrição')),
                ('directions', models.TextField(help_text='Passos para o preparo.', verbose_name='preparo')),
                ('slug', models.SlugField(editable=False, max_length=64, unique=True)),
                ('font', models.CharField(blank=True, help_text='Livro de receita, link do youtube e etc.', max_length=64, null=True, verbose_name='Fonte')),
                ('draft', models.BooleanField(help_text='Se a receita é um rascunho', verbose_name='Rascunho')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(help_text='Quantidade relacionado a métrica', verbose_name='Quantidade')),
                ('metric_type', models.CharField(choices=[('Kg', 'Kilograma'), ('L', 'Litro')], help_text='kg, mg, litro, ml', max_length=2, verbose_name='Tipo de métrica')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ingrediente de receita',
                'verbose_name_plural': 'Ingredientes de receita',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='ingredients.Ingredient'),
        ),
    ]
