# Generated by Django 5.0.2 on 2024-06-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import magapp.base.utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'abbr',
                    models.CharField(
                        help_text='Abreviação da métrica.',
                        max_length=10,
                        verbose_name='Abreviação',
                    ),
                ),
                (
                    'name',
                    magapp.base.utils.models.LowerCharField(
                        help_text='Nome da métrica', max_length=20, verbose_name='nome'
                    ),
                ),
            ],
            options={
                'verbose_name': 'métrica',
                'verbose_name_plural': 'métricas',
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'name',
                    magapp.base.utils.models.LowerCharField(
                        help_text='Qualificador do ingrediente',
                        max_length=64,
                        verbose_name='nome',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Qualificador',
                'verbose_name_plural': 'Qualificadores',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'title',
                    magapp.base.utils.models.LowerCharField(
                        help_text='Título da receita.',
                        max_length=64,
                        verbose_name='título',
                    ),
                ),
                (
                    'description',
                    models.TextField(help_text='Breve descrição da receita', verbose_name='descrição'),
                ),
                (
                    'directions',
                    models.TextField(help_text='Passos para o preparo.', verbose_name='preparo'),
                ),
                ('slug', models.SlugField(editable=False, max_length=64, unique=True)),
                (
                    'font',
                    models.CharField(
                        blank=True,
                        help_text='Livro de receita, link do youtube e etc.',
                        max_length=200,
                        null=True,
                        verbose_name='Fonte',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'qtd',
                    models.IntegerField(
                        help_text='Quantidade relacionado a métrica',
                        verbose_name='Quantidade',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ingredients.ingredient',
                    ),
                ),
                (
                    'metric',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.metric'),
                ),
                (
                    'qualifiers',
                    models.ManyToManyField(blank=True, to='recipes.qualifier'),
                ),
                (
                    'recipe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ingredients',
                        to='recipes.recipe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ingrediente de receita',
                'verbose_name_plural': 'Ingredientes de receita',
            },
        ),
    ]
