# Generated by Django 4.0.10 on 2023-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='font',
            field=models.CharField(blank=True, help_text='Livro de receita, link do youtube e etc.', max_length=200, null=True, verbose_name='Fonte'),
        ),
    ]
