# Generated by Django 3.1.13 on 2021-11-20 22:56

import uuid

import django.db.models.deletion
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_recipe'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(help_text='Quantidade relacionado a métrica', verbose_name='Quantidade')),
                ('metric_type', models.CharField(choices=[('Kg', 'Kilograma'), ('L', 'Litro')], help_text='kg, mg, litro, ml', max_length=2, verbose_name='Tipo de métrica')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ingrediente de receita',
                'verbose_name_plural': 'Ingredientes de receita',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='ingredients.Ingredient'),
        ),
    ]
