# Generated by Django 4.0.4 on 2022-08-02 21:34

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='Qualificador do ingrediente', max_length=64, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Qualificador',
                'verbose_name_plural': 'Qualificadores',
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='qualifiers',
            field=models.ManyToManyField(blank=True, to='recipes.qualifier'),
        ),
    ]
