# Generated by Django 4.0.4 on 2022-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='recipe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='draft',
            field=models.BooleanField(help_text='Se é um rascunho', verbose_name='Rascunho'),
        ),
    ]
