# Generated by Django 5.1.5 on 2025-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_rename_created_by_recipe_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(
                choices=[('private', 'Privada'), ('public', 'Pública')],
                default='private',
                help_text='Se a receita é pública.',
                max_length=10,
            ),
        ),
    ]
