# Generated by Django 4.0.5 on 2022-09-26 10:05

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tagulous_recipe_tags_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='tags da receita', null=None, to='recipes.tagulous_recipe_tags'),
        ),
    ]
