#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Running migrations..."
python manage.py migrate

echo "Starting marimo"
exec marimo edit &> /dev/null & # Ignora a saida mandando para /dev/null

echo "Starting runserver"
exec python manage.py runserver_plus 0.0.0.0:8000