# Generated by Django 5.1.5 on 2025-04-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='created_by',
            new_name='owner',
        ),
    ]
