# Generated by Django 4.0.4 on 2022-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
