# Generated by Django 5.0.2 on 2024-05-24 12:02
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [UnaccentExtension()]
